package com.focusedapp.smartstudyhub.config.firebase;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.Base64;

import org.apache.commons.lang3.StringUtils;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import com.focusedapp.smartstudyhub.exception.EnvironmentVariableNotFoundException;
import com.google.auth.oauth2.GoogleCredentials;
import com.google.firebase.FirebaseApp;
import com.google.firebase.FirebaseOptions;
import com.google.firebase.messaging.FirebaseMessaging;

import lombok.RequiredArgsConstructor;

@Configuration
@RequiredArgsConstructor
public class FirebaseConfig {
	
	@Bean
	FirebaseMessaging firebaseMessaging() throws IOException {
		
		String base64ServiceAccount = "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAic21hcnRzdHVkeWh1YnByb2plY3QiLAogICJwcml2YXRlX2tleV9pZCI6ICI2MGUzYjhiN2VkZWFkMDc1ZDY5OWY1ZDcyZjdlNzQ4ZWNhYTM4ZDk0IiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUURERkszeWJJZHRubWhpXG5uV1dvREluSTJqRncyenhZck5EQzEzb3NSVSt3Z0hqOTN6S0tWQTVRYlV6end3bUQweUorTFhPNDJrdktFVFpxXG5JV2QrS3VUM2E2NzJZdysvd0xWOWtUNlorY0ExUWJDdGNxQUZlNmFrekVxSUYvb2x1MENaY2Z5NDAvQ3JzUGlPXG5XK05PMHk5YzRyQWlzSnBQcWd1UWs1OGdsaTVzWFFPWDBQRGxIUnpzMjExdHRYejR2VXp5c1c0RGJrWnMzR2pPXG55VFluUU5CcnZMNjlKSGZmMG9pb2V2Yi9DZDJWN2FxelRmSXNXMWs4NWVGT3JLSU0yVWkrZFpjWEhPbUJFN2dRXG5mRzdqZDRGTERnYk55MTR5cHlycXJraldYdmxzSjA1SlpvbDVmb1JHb0xLQ2NSRWxjMkt2NllPTnFkL3dvWkJZXG40TnBDWlp6M0FnTUJBQUVDZ2dFQVBrMkQ4bGtUOVgveVlaQllMNC8xajBhVUpMRjM5L0FWYWl6TU1ZaGZWNFRvXG5YMWdodVlqMzIxclZDVUxnYnBBSFE1bjdpKzEzNkF5UVB0djFSQmVwOFpVY0YwZHk5N0F4cG0wMU81TEdmcHZBXG5zOXhZVy9mdU5GS2tlUXVEVWZxWU9vbHJoNUgwbXJqVjRRMWFyc21HcGxrbG5LYWZXZEw2aDQyRjlDL1NtcnVZXG50SlZMemxoUjlUMHVUL3NnaEtUQjF4VHgxVkcwL3RvZmdDbXZDQjV2QWk2RFVOditKeENkVmdXV0JWeEVSRmZ3XG5STmxicWxHSlpaUER5WkJuMm9hZVR5MVJZM3l4blBOS25NZ0l0N29DUmFjU3Q3M2lQYVoxc0VkYklBdzIrcllnXG5kclpLSVBjN3dtZ3JqZW9Sdm5YRVpnelREejEzTFBOYS9Delo4UnFJV1FLQmdRRDFYZGxXOTBqckkxNTVHRTlaXG5Bd0JnbTdDRXp4L1JCUVdlVncrWWd1OGhxOFV1QkVPakpkcWU0RXNjNUxSUDZySHJrc1phRlNJNVV2ZUNxRG9ZXG53RXB4cW5YRGVDeldiSHZnU2FUclJ4aE5vbE8xczlpcTdQSW1Qa2c2ODQ1cS9xSmVCWW8wMGZtbmRDaW1nVTliXG5QT2tWVkNrLzVNbWFUenBsa29rNVNoekFmd0tCZ1FETGlQTFZJeWtSUnNZaFdJR2l1djdXQlRTZjNVSWVybXFTXG52VzFSRkJrakthWDZrSGFoSXJSMThPRlkyTWRrTmZFdmNMNnRFSXgydUxycWJ3bndMam05T3dJbVZEWTJNeXBqXG5KY2JYNUNKZGMwWTQzOFV3YWJOS0g3MzcxeVJtTTN0cnM2eEc5djNHYWM4OFdLTDBBU3JKU09BOXBDa2xJa1NZXG4ybDNLc0xEbmlRS0JnUURjRHJ4eTg3c1JNQnAxcnFqVFl3Nitsa05kQ1VvMnN6TlR6Qzh2a0JhWjh5MFgxVGs0XG5KQ1lMb1l1Y01UM0tBdXBwSmEwQmM3eksvcTcvSHBOa1NXazZ3aTkyRE56aHZrL25Xd1V2QWdjNDhXSDBMNFVkXG4zdjVaOERmbHJ6UkduM0xOc2xnK2dTZFAyS3p3a0Q2MHpFOGJFdTBmNGJneHplYkkzQUI0UWhEQlR3S0JnRUEvXG5IMS9WOUcybXFIMzRJUnVMNlVzSFk2QWV5SE5FM1JFcXlDbnlyU2lqU2VnNDE2bHZlZ1ZNbnVWYnNEemFwaUl5XG5kWTNOam5rZlFLa2xtYjU5Nk8zcGhYa3gxZGJ2K2E1SVMyYjBkVUNJVlo4NFMxZEgxamRNbzd5dUlhZzlFZlZpXG5Scnd6MU5GZnJ2RytqTmwyME5tdXJsSG0wcklOQ2hneHZhOXdiTGI1QW9HQkFPOTBabTBwbVN6N1NwUkt4ZTdvXG5LL0haL3d0dmVlREg5aTlHbUJsQjVmbkRhZTlubDZvdGFuYUttOHpDYWtITDh2WkZRTlpVRjN0a08xNXZEQVVnXG5CWmtZNUZLV3RlQ04xQ250V2ZsaHg2ODlXU29UYWhDeDJDWkh3SERuWHdDMDIxR3oxekFXUnllUElDTDU4bXhVXG5FbzBnNjRvZUdMVlMwZ3Izc1p2VHBCSGpcbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJmaXJlYmFzZS1hZG1pbnNkay1mbmVucUBzbWFydHN0dWR5aHVicHJvamVjdC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMTY3MTI3NjE2MDk0MTE2ODQ5NjgiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2ZpcmViYXNlLWFkbWluc2RrLWZuZW5xJTQwc21hcnRzdHVkeWh1YnByb2plY3QuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0=";
		// base64ServiceAccount = base64ServiceAccount.concat(System.getenv("FIREBASE_SERVICE_ACCOUNT_KEY_SECOND"));
		if (StringUtils.isBlank(base64ServiceAccount)) {
            throw new EnvironmentVariableNotFoundException("Environment variable FIREBASE_SERVICE_ACCOUNT_KEY not found.");
        }
		byte[] decodedBytes = Base64.getDecoder().decode(base64ServiceAccount);
        ByteArrayInputStream serviceAccountStream = new ByteArrayInputStream(decodedBytes);
        
		GoogleCredentials googleCredentials = GoogleCredentials.fromStream(serviceAccountStream);
		FirebaseOptions firebaseOptions = FirebaseOptions.builder()
				.setCredentials(googleCredentials).build();
		FirebaseApp app = FirebaseApp.initializeApp(firebaseOptions, "my-app");
		return FirebaseMessaging.getInstance(app);
	}
	
}
