name: Build & Deploy Spring app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring Boot API for app SmartStudyHub
    runs-on: ubuntu-latest
    env: 
      SMARTSTUDYHUB_JWT_SECRET_KEY: ${{secrets.SMARTSTUDYHUB_JWT_SECRET_KEY}}
      SMARTSTUDYHUB_USERNAME_DATABASE: ${{secrets.SMARTSTUDYHUB_USERNAME_DATABASE}}
      SMARTSTUDYHUB_PASSWORD_DATABASE: ${{secrets.SMARTSTUDYHUB_PASSWORD_DATABASE}}
      SMARTSTUDYHUB_USERNAME_MAIL: ${{secrets.SMARTSTUDYHUB_USERNAME_MAIL}}
      SMARTSTUDYHUB_PASSWORD_MAIL: ${{secrets.SMARTSTUDYHUB_PASSWORD_MAIL}}
      SMARTSTUDYHUB_GOOGLE_CLIENTID: ${{secrets.SMARTSTUDYHUB_GOOGLE_CLIENTID}}
      SMARTSTUDYHUB_GOOGLE_CLIENTSECRET: ${{secrets.SMARTSTUDYHUB_GOOGLE_CLIENTSECRET}}
      SMARTSTUDYHUB_GITHUB_CLIENTID: ${{secrets.SMARTSTUDYHUB_GITHUB_CLIENTID}}
      SMARTSTUDYHUB_GITHUB_CLIENTSECRET: ${{secrets.SMARTSTUDYHUB_GITHUB_CLIENTSECRET}}
      SMARTSTUDYHUB_FACEBOOK_CLIENTID: ${{secrets.SMARTSTUDYHUB_FACEBOOK_CLIENTID}}
      SMARTSTUDYHUB_FACEBOOK_CLIENTSECRET: ${{secrets.SMARTSTUDYHUB_FACEBOOK_CLIENTSECRET}}
      SMARTSTUDYHUB_CLOUDINARY_CLOUDNAME: ${{secrets.SMARTSTUDYHUB_CLOUDINARY_CLOUDNAME}}
      SMARTSTUDYHUB_CLOUDINARY_APIKEY: ${{secrets.SMARTSTUDYHUB_CLOUDINARY_APIKEY}}
      SMARTSTUDYHUB_CLOUDINARY_APISECRET: ${{secrets.SMARTSTUDYHUB_CLOUDINARY_APISECRET}}
      SMARTSTUDYHUB_VNPAY_TMNCODE: ${{secrets.SMARTSTUDYHUB_VNPAY_TMNCODE}}
      SMARTSTUDYHUB_VNPAY_HASHSECRET: ${{secrets.SMARTSTUDYHUB_VNPAY_HASHSECRET}}
      SMARTSTUDYHUB_PAYPAL_CLIENTID: ${{secrets.SMARTSTUDYHUB_PAYPAL_CLIENTID}}
      SMARTSTUDYHUB_PAYPAL_CLIENTSECRET: ${{secrets.SMARTSTUDYHUB_PAYPAL_CLIENTSECRET}}
      SMARTSTUDYHUB_OPENAI_APIKEY: ${{secrets.SMARTSTUDYHUB_OPENAI_APIKEY}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          
      - name: Unit Tests
        run: mvn -B test --file pom.xml
        
      - name: Clean the application
        run: 
          mvn clean --file pom.xml
          
      - name: Build the application
        run: 
          mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/appsmartstudyhub:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/appsmartstudyhub:latest